#include <GUIConstantsEx.au3>
#include <WindowsConstants.au3>
#include <Misc.au3>
#Region (=== GUI generated by GuiBuilderPlus 1.2.0 ===)
Global $hGUI
Global $Label_counter
Global $Combo_enemie
Global $Checkbox_bring_to_front
Global $Checkbox_alert_last_tree_sec
Global $iniFilePath = "config.ini"
Global $spawntimeFromIni

Func _guiCreate()
	
	$hGUI = GUICreate("Spawn Alert", 300, 300, 210, 0)
	$Label_header = GUICtrlCreateLabel("Spawn Alert", 50, 10, 300, 50)
	GUICtrlSetFont(-1, 25, 700)
	$Combo_enemie = GUICtrlCreateCombo("Select enemy", 25, 75, 250, 20)
	$Checkbox_bring_to_front = GUICtrlCreateCheckbox("Bring New World to front!", 25, 100, 300, 20)
	$Label_counter = GUICtrlCreateLabel("Counter", 25, 150, 250, 100)
	GUICtrlSetFont(-1, 16, 700)
	
	$Label_info = GUICtrlCreateLabel("Press Ctrl + W to start timer for selected enemy.", 35, 250, 300, 20)
	fillEnemiesCombo()
EndFunc
#EndRegion (=== GUI generated by GuiBuilderPlus 1.2.0 ===)

_main()

Func _main()
	_guiCreate()
	GUISetState(@SW_SHOWNORMAL)

	While 1
		Switch GUIGetMsg()
			Case $GUI_EVENT_CLOSE
				ExitLoop

			Case Else
				HotKeySet("^w", "StartTimer")
		EndSwitch
	WEnd
EndFunc

Func fillEnemiesCombo()
	Local $sectionList = IniReadSectionNames($iniFilePath)
	Local $message
	If Not @error Then
		For $i = 1 To $sectionList[0]
			$message = $message & "|" & $sectionList[$i]
		Next
	EndIf
	$message = "|Select enemy" & $message
	GUICtrlSetData($Combo_enemie, $message, "Select enemy")
	ConsoleWrite($message)
EndFunc
	

Func StartTimer()
    Local $timer = TimerInit()
	ConsoleWrite(GUICtrlRead($Combo_enemie) & @CRLF)
	Local $iTimerOfEnemie = Int(0)
	
	$spawntimeFromIni = IniRead($iniFilePath, GUICtrlRead($Combo_enemie), "spawnTime", 0)
	
	$iTimerOfEnemie = Int($spawntimeFromIni) * 1000
	
    While TimerDiff($timer) < $iTimerOfEnemie
        Sleep(100)
		$seconds=Round(TimerDiff($timer)/1000,0)
		$timerOfEnemieAsSecound =  Round($iTimerOfEnemie/1000,0)
		$result = $timerOfEnemieAsSecound - $seconds
		GUICtrlSetData($Label_counter, GUICtrlRead($Combo_enemie) & " respawn in " & $result & " secounds !")
    WEnd

    playSound()
	bringToFront()

EndFunc

Func playSound()
    Local $soundFile = "sounds\alertsound.wav"
    SoundPlay($soundFile)
EndFunc

Func bringToFront()
	If GUICtrlRead($Checkbox_bring_to_front) = $GUI_CHECKED Then
		Local $windowTitle = "New World"
		WinActivate($windowTitle)
	EndIf
EndFunc